#version 430

layout (local_size_x = 20, local_size_y = 20) in;
layout (std430, binding = 0) buffer InBuffer { float matrixA[];};
layout (std430, binding = 1) buffer OutBuffer {float matrixB[];};

void main() 
{

    uint glindex = gl_GlobalInvocationID.y * gl_WorkGroupSize.x + gl_GlobalInvocationID.x;

    uint lengthLine = 20;
    uint i = glindex / lengthLine;
    uint j = glindex % lengthLine;

    uint newIndex = j * lengthLine + i;
    matrixB[newIndex] = matrixA[glindex];
}
